fixtures:
  symlinks:
    icinga: "#{source_dir}"
  repositories:
  forge_modules:
    stdlib: "puppetlabs-stdlib"
    staging: "puppet-staging"
    mysql: "puppetlabs-mysql"
    concat: "puppetlabs-concat"
